version: '2'
servieces:
  jenkins:
    image: 'jenkins/jenkins'
    container_name: "jenkins"
    labels:
      Kompose.service.type: nodeport
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - /srv/data/jenkins_data:/jenkins_home
      - /srv/data/jenkins:/var/jenkins_config
      
volumes:
  jenkins_data:
    driver: local
